// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: proto/shorturl_service/v1/shorturl.proto

package shorturl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShortUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlLong string `protobuf:"bytes,1,opt,name=url_long,json=urlLong,proto3" json:"url_long,omitempty"`
}

func (x *CreateShortUrlRequest) Reset() {
	*x = CreateShortUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortUrlRequest) ProtoMessage() {}

func (x *CreateShortUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortUrlRequest.ProtoReflect.Descriptor instead.
func (*CreateShortUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShortUrlRequest) GetUrlLong() string {
	if x != nil {
		return x.UrlLong
	}
	return ""
}

type CreateShortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlLong   string                 `protobuf:"bytes,1,opt,name=url_long,json=urlLong,proto3" json:"url_long,omitempty"`
	UrlShort  string                 `protobuf:"bytes,2,opt,name=url_short,json=urlShort,proto3" json:"url_short,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *CreateShortResponse) Reset() {
	*x = CreateShortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShortResponse) ProtoMessage() {}

func (x *CreateShortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShortResponse.ProtoReflect.Descriptor instead.
func (*CreateShortResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShortResponse) GetUrlLong() string {
	if x != nil {
		return x.UrlLong
	}
	return ""
}

func (x *CreateShortResponse) GetUrlShort() string {
	if x != nil {
		return x.UrlShort
	}
	return ""
}

func (x *CreateShortResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetShortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlShort string `protobuf:"bytes,1,opt,name=url_short,json=urlShort,proto3" json:"url_short,omitempty"`
}

func (x *GetShortRequest) Reset() {
	*x = GetShortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortRequest) ProtoMessage() {}

func (x *GetShortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortRequest.ProtoReflect.Descriptor instead.
func (*GetShortRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *GetShortRequest) GetUrlShort() string {
	if x != nil {
		return x.UrlShort
	}
	return ""
}

type GetShortRespons struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlLong   string                 `protobuf:"bytes,1,opt,name=url_long,json=urlLong,proto3" json:"url_long,omitempty"`
	UrlShort  string                 `protobuf:"bytes,2,opt,name=url_short,json=urlShort,proto3" json:"url_short,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *GetShortRespons) Reset() {
	*x = GetShortRespons{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShortRespons) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortRespons) ProtoMessage() {}

func (x *GetShortRespons) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortRespons.ProtoReflect.Descriptor instead.
func (*GetShortRespons) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *GetShortRespons) GetUrlLong() string {
	if x != nil {
		return x.UrlLong
	}
	return ""
}

func (x *GetShortRespons) GetUrlShort() string {
	if x != nil {
		return x.UrlShort
	}
	return ""
}

func (x *GetShortRespons) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_shorturl_service_v1_shorturl_proto protoreflect.FileDescriptor

var file_proto_shorturl_service_v1_shorturl_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x72, 0x6c, 0x4c, 0x6f, 0x6e, 0x67, 0x22, 0x88, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x72,
	0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x2e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x72, 0x6c, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x22, 0x84, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x72, 0x6c, 0x5f, 0x6c, 0x6f,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x6f, 0x6e,
	0x67, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x72, 0x6c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xf0, 0x01, 0x0a, 0x0f, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x74, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12,
	0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75,
	0x72, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x72, 0x6c, 0x12, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74,
	0x75, 0x72, 0x6c, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24,
	0x70, 0x72, 0x61, 0x69, 0x73, 0x69, 0x6e, 0x64, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_shorturl_service_v1_shorturl_proto_rawDescOnce sync.Once
	file_proto_shorturl_service_v1_shorturl_proto_rawDescData = file_proto_shorturl_service_v1_shorturl_proto_rawDesc
)

func file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP() []byte {
	file_proto_shorturl_service_v1_shorturl_proto_rawDescOnce.Do(func() {
		file_proto_shorturl_service_v1_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shorturl_service_v1_shorturl_proto_rawDescData)
	})
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescData
}

var file_proto_shorturl_service_v1_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shorturl_service_v1_shorturl_proto_goTypes = []any{
	(*CreateShortUrlRequest)(nil), // 0: proto.shorturl_service.v1.CreateShortUrlRequest
	(*CreateShortResponse)(nil),   // 1: proto.shorturl_service.v1.CreateShortResponse
	(*GetShortRequest)(nil),       // 2: proto.shorturl_service.v1.GetShortRequest
	(*GetShortRespons)(nil),       // 3: proto.shorturl_service.v1.GetShortRespons
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_shorturl_service_v1_shorturl_proto_depIdxs = []int32{
	4, // 0: proto.shorturl_service.v1.CreateShortResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: proto.shorturl_service.v1.GetShortRespons.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: proto.shorturl_service.v1.ShortUrlService.CreateShortUrl:input_type -> proto.shorturl_service.v1.CreateShortUrlRequest
	2, // 3: proto.shorturl_service.v1.ShortUrlService.GetShortUrl:input_type -> proto.shorturl_service.v1.GetShortRequest
	1, // 4: proto.shorturl_service.v1.ShortUrlService.CreateShortUrl:output_type -> proto.shorturl_service.v1.CreateShortResponse
	3, // 5: proto.shorturl_service.v1.ShortUrlService.GetShortUrl:output_type -> proto.shorturl_service.v1.GetShortRespons
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_shorturl_service_v1_shorturl_proto_init() }
func file_proto_shorturl_service_v1_shorturl_proto_init() {
	if File_proto_shorturl_service_v1_shorturl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateShortUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateShortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetShortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetShortRespons); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shorturl_service_v1_shorturl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shorturl_service_v1_shorturl_proto_goTypes,
		DependencyIndexes: file_proto_shorturl_service_v1_shorturl_proto_depIdxs,
		MessageInfos:      file_proto_shorturl_service_v1_shorturl_proto_msgTypes,
	}.Build()
	File_proto_shorturl_service_v1_shorturl_proto = out.File
	file_proto_shorturl_service_v1_shorturl_proto_rawDesc = nil
	file_proto_shorturl_service_v1_shorturl_proto_goTypes = nil
	file_proto_shorturl_service_v1_shorturl_proto_depIdxs = nil
}
