version: "3.8"
services:
  redis:
    image: redis:5.0.12
    container_name: redis    
    command: redis-server --requirepass redispass
    ports:
      - 6378:6379
    # networks:
    #   networktinyurl:
    #     ipv4_address: 172.22.0.3  

  postgres:
    image: postgres
    container_name: postgres   
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data     
    # command: -p 5434
    # networks:
    #   networktinyurl:
    #     ipv4_address: 172.22.0.4  

  app:
    container_name: app-tinyurl
    build:
      context: .
      dockerfile: Dockerfile    
    image: app-tinyurl:latest
    ports:
      - "8383:8080"
      - "50053:50052"
    # environment:
      # - POSTGRES_HOST=postgres
      # - POSTGRES_PORT=5434
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=password
      # - REDIS_HOST=172.22.0.3
      # - REDIS_PASSWORD=redispass      
    depends_on:
      - postgres
      - redis
    # networks:
    #   networktinyurl:
    #     ipv4_address: 172.22.0.5  

# networks:
#   networktinyurl:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.22.0.0/16

volumes:
  postgres_data: